### ISSUE TITLE
Special rank doesn't work

### ISSUE THREAD

**Issue by condolent** [popoklopsi/Stamm#21]
Hi. I'm trying to use the teleport feature that I've set to only give access to a "admin" rank. That rank is given to those with the flag z.
This is how it looks in my StammLevels.txt
`"admin"
	{
	  	"name"              "Admin"
	  	"flag"              "b"
	}`

I have the z-flag and cannot use the !stele command in csgo..

Is there a way to see which ranks a user is in? I can see the feature in the admin-feature list at !sinfo but it doesn't seem like I've been added to the admin-group.

How can I fix this?

EDIT: I can add that z-flag is the only flag I've given myself. Don't think I need to have every flag on my steamID for this to work, z-flag is supposed to give every flag. Right?

**Comment by popoklopsi** [comment]
This section is only for issues with the code, for general question please post this in the forum
